SELECT * FROM TESTERS
UNION
SELECT * FROM DEVELOPERS;


SELECT * FROM TESTERS
UNION ALL
SELECT * FROM DEVELOPERS;


SELECT NAMES FROM TESTERS
MINUS
SELECT NAMES FROM DEVELOPERS;


SELECT NAMES FROM TESTERS
INTERSECT
SELECT NAMES FROM DEVELOPERS;


--how to find duplicate names in employees name
--(FAMOUS INTERVIEW QUESTION)
SELECT FIRST_NAME, COUNT(*)
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*)>1;