--1-FIND THE HIGHEST 14TH SALARY

--list salary high to low without duplicate values
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

--find the highest 14th salary (removing duplicate values)
SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM<15;



--2-FIND THE EMPLOYEE INFO WHO IS MAKING 14 THE HIGHEST SALARY (with duplicates)
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
                FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
                WHERE ROWNUM <15);