SELECT * FROM SCRUMTEAM;

--adding new column
ALTER TABLE SCRUMTEAM ADD SALARY INTEGER;

UPDATE SCRUMTEAM SET SALARY = 100000 WHERE EMP_ID=1;
UPDATE SCRUMTEAM SET SALARY = 90000 WHERE EMP_ID=2;
UPDATE SCRUMTEAM SET SALARY = 120000 WHERE EMP_ID=3;

--rename the column
ALTER TABLE SCRUMTEAM RENAME COLUMN SALARY TO ANNUAL_SALARY;

--delete,drop column
ALTER TABLE SCRUMTEAM DROP COLUMN ANNUAL_SALARY;

--how to change table name?
ALTER TABLE SCRUMTEAM RENAME TO AGILETEAM;

SELECT * FROM AGILETEAM;

COMMIT;

--truncate: if we want to delete all data from the table, but we still keep the table structure we use truncate
TRUNCATE TABLE AGILETEAM;

--drop table: if we want to delete the table and the data together
DROP TABLE AGILETEAM;

